name: Publish Android Library

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to publish'
        required: false
        type: string
      branch:
        description: 'Git branch to publish'
        required: false
        type: string
      commit:
        description: 'Git commit hash to publish'
        required: false
        type: string
      version:
        description: 'Custom artifact version (optional)'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up Maven settings
        run: |
            mkdir -p ~/.m2
            echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\">" > ~/.m2/settings.xml
            echo "  <servers>" >> ~/.m2/settings.xml
            echo "    <server>" >> ~/.m2/settings.xml
            echo "      <id>somewear-artifacts</id>" >> ~/.m2/settings.xml
            echo "      <username>${{ secrets.MAVEN_USERNAME }}</username>" >> ~/.m2/settings.xml
            echo "      <password>${{ secrets.MAVEN_PASSWORD }}</password>" >> ~/.m2/settings.xml
            echo "    </server>" >> ~/.m2/settings.xml
            echo "  </servers>" >> ~/.m2/settings.xml
            echo "</settings>" >> ~/.m2/settings.xml

      - name: Check out specific ref
        run: |
          if [[ "${{ inputs.tag }}" != "" ]]; then
            git checkout tags/${{ inputs.tag }}
          elif [[ "${{ inputs.branch }}" != "" ]]; then
            git checkout ${{ inputs.branch }}
          elif [[ "${{ inputs.commit }}" != "" ]]; then
            git checkout ${{ inputs.commit }}
          else
            echo "No tag, branch, or commit specified. Aborting."
            exit 1
          fi

      - name: Build and Publish Library
        run: |
          ./gradlew lib:dfu:assemble
          ./gradlew lib:dfu:publish \
            -Pmaven.repo.url=https://somewear-artifacts.appspot.com \
            -Pmaven.repo.username=${{ secrets.MAVEN_USERNAME }} \
            -Pmaven.repo.password=${{ secrets.MAVEN_PASSWORD }}

      - name: Confirm Success
        run: echo "Library published successfully."
